---
title: "Apoxalypse: Evaluating the evolution and transmission dynamics of Mpox and its pandemic potential"
---

## Additional references
  
- Akhmetzhanov, A. R., & Wu, P.-H. (2024). Transmission potential of mpox in mainland China, June-July 2023: Estimating reproduction number during the initial phase of the epidemic. PeerJ, 12, e16908. https://doi.org/10.7717/peerj.16908 
Article | Infectious Diseases | JAMA Pediatrics | JAMA Network. (n.d.). Retrieved September 24, 2024, from https://jamanetwork.com/journals/jamapediatrics/fullarticle/486169 
- Assiri, A. M., Alserehi, H., Abuhasan, M. Y., Khalil, E. A. A., Al-Thunayan, M. H., Alshehri, M. S., Alrossais, A. - A., Abudahish, A. S., Alsahafi, A. J., & Al-Tawfiq, J. A. (2024). Epidemiology, clinical presentation, and outcome of mpox: A study of 381 cases in Saudi Arabia. IJID Regions, 11, 100358. https://doi.org/10.1016/j.ijregi.2024.100358 
- Besombes, C., Mbrenga, F., Malaka, C., Gonofio, E., Schaeffer, L., Konamna, X., Selekon, B., Namsenei-Dankpea, J., - Gildas Lemon, C., Landier, J., von Platen, C., Gessain, A., Manuguerra, J. C., Fontanet, A., & Nakouné, E. (2023). Investigation of a mpox outbreak in Central African Republic, 2021-2022. One Health, 16, 100523. https://doi.org/10.1016/j.onehlt.2023.100523 
- Clinical manifestations and outcome of Mpox infection in Qatar: An observational study during the 2022 outbreak—ClinicalKey. (n.d.). Retrieved September 24, 2024, from https://www.clinicalkey.com/#!/content/playContent/1-s2.0-S1876034123003076?returnurl=https:%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS1876034123003076%3Fshowall%3Dtrue&referrer= 
- Díaz-Brochero, C., & Cucunubá, Z. M. (2024). Epidemiological findings, estimates of the instantaneous reproduction number, and control strategies of the first Mpox outbreak in Latin America. Travel Medicine and Infectious Disease, 59, 102701. https://doi.org/10.1016/j.tmaid.2024.102701 
- Djuicy, D. D., Sadeuh-Mba, S. A., Bilounga, C. N., Yonga, M. G., Tchatchueng-Mbougua, J. B., Essima, G. D., Esso, L., Nguidjol, I. M. E., Metomb, S. F., Chebo, C., Agwe, S. M., Ankone, P. A., Ngonla, F. N. N., Mossi, H. M., Etoundi, A. G. M., Eyangoh, S. I., Kazanji, M., & Njouom, R. (n.d.). Concurrent Clade I and Clade II Monkeypox Virus Circulation, Cameroon, 1979–2022—Volume 30, Number 3—March 2024—Emerging Infectious Diseases journal—CDC. https://doi.org/10.3201/eid3003.230861 
- Doshi, R. H., Guagliardo, S. A. J., Doty, J. B., Babeaux, A. D., Matheny, A., Burgado, J., Townsend, M. B., Morgan, C. N., Satheshkumar, P. S., Ndakala, N., Kanjingankolo, T., Kitembo, L., Malekani, J., Kalemba, L., Pukuta, E., N’kaya, T., Kangoula, F., Moses, C., McCollum, A. M., … Petersen, B. W. (n.d.). Epidemiologic and Ecologic Investigations of Monkeypox, Likouala Department, Republic of the Congo, 2017—Volume 25, Number 2—February 2019—Emerging Infectious Diseases journal—CDC. https://doi.org/10.3201/eid2502.181222 
- Epidemiological update – Week 35/2024: Mpox due to monkeypox virus clade I. (2024, September 2). https://www.ecdc.europa.eu/en/news-events/mpox-epidemiological-update-monkeypox-2-september-2024 
- Erez, N., Achdout, H., Milrot, E., Schwartz, Y., Wiener-Well, Y., Paran, N., Politi, B., Tamir, H., Israely, T., Weiss, S., Beth-Din, A., Shifman, O., Israeli, O., Yitzhaki, S., Shapira, S. C., Melamed, S., & Schwartz, E. (n.d.). Diagnosis of Imported Monkeypox, Israel, 2018—Volume 25, Number 5—May 2019—Emerging Infectious Diseases journal—CDC. https://doi.org/10.3201/eid2505.190076 
- Formenty, P., Muntasir, M. O., Damon, I. K., Chowdhary, V., Opoka, M. L., Monimart, C., Mutasim, E. M., Manuguerra, J.-C., Davidson, W. B., Karem, K. L., Cabeza, J., Wang, S., Malik, M. R., Durand, T., Khalid, A., Rioton, T., Kuong-Ruay, A., Babiker, A. A., Karsani, M. E. M., & Abdalla, M. S. (n.d.). Human Monkeypox Outbreak Caused by Novel Virus Belonging to Congo Basin Clade, Sudan, 2005—Volume 16, Number 10—October 2010—Emerging Infectious Diseases journal—CDC. https://doi.org/10.3201/eid1610.100713 
- Harrison, L. B., Bergeron, G., Cadieux, G., Charest, H., Fafard, J., Levade, I., Blais, A. C., Huchet, E., Trottier, B., Vlad, D., Szabo, J., Thomas, R., Poulin, S., Greenaway, C., Zaharatos, G. J., Oughton, M., Chakravarti, A., Pilarski, R., Bui-Nguyen, A., … Barkati, S. (2023). Monkeypox in Montréal: Epidemiology, Phylogenomics, and Public Health Response to a Large North American Outbreak. Annals of Internal Medicine, 176(1), 67–76. https://doi.org/10.7326/M22-2699 
- Kalthan, E., Tenguere, J., Ndjapou, S. G., Koyazengbe, T. A., Mbomba, J., Marada, R. M., Rombebe, P., Yangueme, P., Babamingui, M., Sambella, A., & Nakoune, E. R. (2018). Investigation of an outbreak of monkeypox in an area occupied by armed groups, Central African Republic. Médecine et Maladies Infectieuses, 48(4), 263–268. https://doi.org/10.1016/j.medmal.2018.02.010 
- Kile, J. C., Fleischauer, A. T., Beard, B., Kuehnert, M. J., Kanwal, R. S., Pontones, P., Messersmith, H. J., Teclaw, R., Karem, K. L., Braden, Z. H., Damon, I., Khan, A. S., & Fischer, M. (2005). Article. Archives of Pediatrics & Adolescent Medicine, 159(11), 1022–1025. https://doi.org/10.1001/archpedi.159.11.1022 
- Learned, L., Reynolds, M., Wassa, D., Li, Y., Olson, V., Karem, K., Stempora, L., Braden, Z., Kline, R., Likos, A., Libama, F., Moudzeo, H., Bolanda, J., Tarangonia, P., Boumandoki, P., Formenty, P., Harvey, J., & Damon, I. (2005). Extended Interhuman Transmission Of Monkeypox In A Hospital Community In The Republic Of The Congo, 2003. The American Journal of Tropical Medicine and Hygiene, 73, 428–434. https://doi.org/10.4269/ajtmh.2005.73.428 
- Mpox outbreak control indicators used in Ontario, Canada: May 21–December 10, 2022—Zygmunt—2023—Journal of Medical Virology—Wiley Online Library. (n.d.). Retrieved September 24, 2024, from https://onlinelibrary.wiley.com/doi/10.1002/jmv.29251 
- Nolen, L. D., Osadebe, L., Katomba, J., Likofata, J., Mukadi, D., Monroe, B., Doty, J. B., Hughes, C. M., Kabamba, J., Malekani, J., Bomponda, P. L., Lokota, J. I., Balilo, M. P., Likafi, T., Lushima, R. S., Ilunga, B. K., Nkawa, F., Pukuta, E., Karhemere, S., … Reynolds, M. G. (n.d.). Extended Human-to-Human Transmission during a Monkeypox Outbreak in the Democratic Republic of the Congo—Volume 22, Number 6—June 2016—Emerging Infectious Diseases journal—CDC. https://doi.org/10.3201/eid2206.150579 
- Ogoina, D., & James, H. I. (2023). Mpox among Linked Heterosexual Casual Partners in Bayelsa, Nigeria. New England Journal of Medicine, 388(22), 2101–2104. https://doi.org/10.1056/NEJMc2300866 
- Outbreak of human monkeypox in Nigeria in 2017–18: A clinical and epidemiological report—The Lancet Infectious Diseases. (n.d.). Retrieved September 24, 2024, from https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(19)30294-4/fulltext 
- Saldaña, F., Daza-Torres, M. L., & Aguiar, M. (2023). Data-driven estimation of the instantaneous reproduction number and growth rates for the 2022 monkeypox outbreak in Europe. PLOS ONE, 18(9), e0290387. https://doi.org/10.1371/journal.pone.0290387 
- Sheffer, R., Savion, M., Nuss, N., Amitai, Z., & Salama, M. (2023). Monkeypox outbreak in the Tel Aviv District, Israel, 2022. International Journal of Infectious Diseases, 128, 88–90. https://doi.org/10.1016/j.ijid.2022.12.023 
- Singh, S., Kumar, R., Singh, S. K., Singh, S., Kumar, R., & Singh, S. K. (2022). All That We Need to Know About the Current and Past Outbreaks of Monkeypox: A Narrative Review. Cureus, 14. https://doi.org/10.7759/cureus.31109 
- “When will it be over?”: An introduction to viral reproduction numbers, R0 and Re | The Centre for Evidence-Based Medicine. (n.d.). Retrieved September 25, 2024, from https://www.cebm.net/covid-19/when-will-it-be-over-an-introduction-to-viral-reproduction-numbers-r0-and-re/ 
- Yinka-Ogunleye, A., Aruna, O., Dalhat, M., Ogoina, D., McCollum, A., Disu, Y., Mamadu, I., Akinpelu, A., Ahmad, A., Burga, J., Ndoreraho, A., Nkunzimana, E., Manneh, L., Mohammed, A., Adeoye, O., Tom-Aba, D., Silenou, B., Ipadeola, O., Saleh, M., … Satheshkumar, P. S. (2019). Outbreak of human monkeypox in Nigeria in 2017–18: A clinical and epidemiological report. The Lancet Infectious Diseases, 19(8), 872–879. https://doi.org/10.1016/S1473-3099(19)30294-4 